name: Compaire functions
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }} # ellが含まれるか
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }} # Heで始まるか
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }} # loで終わるか