name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.SECRETPASS }} # Secretsの参照
    steps:
      - run: echo "${SECRET}" # ログ出力はマスクされる
      - run: echo "${SECRET:0:1} ${SECRET$?}" # ログ出力はマスクされない